### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/layer8_dep#37]
## Description:
The current documentation does not provide clear information about the project's folder structure. This makes it difficult for new contributors to understand where specific files or features should be located.

## Suggested Content:
- A high-level overview of the folder structure.
- A description of what each folder contains and its purpose in the project.
- Examples of where specific files or features might be located.
- Any conventions or rules related to the folder structure.

## Benefits:
- New contributors can quickly understand the project structure.
- It can reduce the time spent searching for specific files or features.
- It can help maintain consistency across the project.

## Additional Context:
Include any other information that might be helpful, like specific areas of the documentation that are lacking, or examples from other projects with good documentation of their folder structure.

**Comment by stravid87** [comment]
@hermannleboss I'm going to take ownership of this task and try to onboard you & the C.F. team.

**Comment by stravid87** [comment]
At present, our only "customers" are our own team members and our only developers are also our only team members.

To use the lyaer8 project, there is to be enough information in the README.md. However comprehensive documentation at this time might be harder to maintain than is to have simple 1-on-1 as people on board with the project.

**Comment by stravid87** [comment]
At present, our only "customers" are our own team members and our only developers are also our only team members.

To use the lyaer8 project, there is to be enough information in the README.md. However comprehensive documentation at this time might be harder to maintain than is to have simple 1-on-1 as people on board with the project.
