### ISSUE TITLE
Making a Compiled TIO L8server.exe Dynamic @ Run Time

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/layer8_dep#51]
Currently (see branch stravid87/run_local) the TIO server can be compiled into an executable that functions. However it does not have a robust set of flags necessary for users to run it with dynamic flags (for such things as PORT, DB credentials, etc) without using a '.env' and this makes it less flexible. Flags and associated documentation should be added so that clients can easily download the executable, configure it, and then start local development.

**Comment by stravid87** [comment]
Another suggestion:  Currently, it is necessary to spin up the TIO-Server with a PG Database. However, the Usecase/Repo code allow for easy configuration of an in memory process that we should create an option for likely with a test Client & test User already preconfigured. 

See Line 58-62 of server/main.go where the PG database is configured.

**Comment by huzaifamk** [comment]
@stravid87 this is achievable now, but I also need to discuss something related to this, which we can do for the next meeting.

**Comment by stravid87** [comment]
Joint agreement that it was preferrable to simple copy the assets folder than it was to embed.
